resolver: ghc-8.0

packages:
  - .
  - haddock-api
  - haddock-library
  - haddock-test

extra-deps:
  - ansi-terminal-0.6.2.3
  - async-2.1.0
  - base-compat-0.9.1
  - ghc-paths-0.1.0.9
  - hspec-2.2.3
  - hspec-core-2.2.3
  - hspec-discover-2.2.3
  - hspec-expectations-0.7.2
  - HUnit-1.3.1.1
  - primitive-0.6.1.0
  - QuickCheck-2.8.2
  - quickcheck-io-0.1.2
  - random-1.1
  - setenv-0.1.1.3
  - stm-2.4.4.1
  - syb-0.6
  - text-1.2.2.1
  - tf-random-0.5
  - xml-1.3.14
